server {
    listen 80;
    index index.php index.html;
    root /var/www/public;
    client_max_body_size 10m;

    gzip on;
    gzip_types application/json text/css application/javascript;
    gzip_min_length 512;

    # Swagger UI servido do vendor (sem CDN)
    location /docs/ui/ {
        alias /var/www/vendor/swagger-api/swagger-ui/dist/;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
